### ISSUE TITLE
日時の表示が見づらい

### ISSUE THREAD

**Issue by DevWithKaiju** [KaijuAtUT/DriveChangeNotifier#1]
## 内容

最終更新日時が (最終更新: Sat Dec 21 2024 01:03:48 GMT+0900 (Japan Standard Time)) のように表示されるが、長くて見づらい。
12/21 01:03 のみにしたい。

**Comment by vvihar** [comment]
日付については
```js
new Date().toLocaleDateString("ja-JP", {year: "numeric", month: "2-digit", day: "2-digit"})
```
とかにするといいと思います。

**Comment by DevWithKaiju** [comment]
おおおお神ですね、ありがとうございます。
